[project]
name = "tinycmb"
version = "0.1.0"
description = "Boilerplate code for CMB analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.2.0",
    "camb>=1.6.5",
    "healpy>=1.19.0",
    "matplotlib>=3.10.8",
    "pysm3>=3.4.3",
]
